import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    final localization = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    if (localization == null) {
      throw FlutterError(
        'AppLocalizations.of() called with a context that does not contain AppLocalizations.\n'
        'Make sure AppLocalizations.delegate is added to the localizationsDelegates list, '
        'and that the context has access to a MaterialApp or CupertinoApp.',
      );
    }
    return localization;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': "Nobetim",
      'resetPassword': 'Reset Password',
      'resetPasswordEmailSent': 'Password reset email sent! Check your inbox.',
      'resetPasswordEmailFail': 'Failed to send reset email. Please try again.',
      'enterEmailToReceive': 'Enter your mail to receive password reset mail',
      'enterYourEmail': 'Enter your email address',
      'sendResetLink': 'Send Reset Link',
      'createAccount': 'Create Account',
      'alreadyHaveAccount': 'Already have an account?',
      'login': 'Log in',
      'login2': 'Log In',
      'nameSurname': 'Name & Surname',
      'jobDescription': 'Job Description',
      'selectBirthday': 'Select Birthday',
      'phoneNumber': 'Phone Number',
      'email': 'Email',
      'password': 'Password',
      'register': 'Register',
      'registrationSuccessful': 'Registration successful!',
      'fillRequiredFields': 'Please fill in all required fields.',
      'errorOccurred': 'An error occurred. Please try again.',
      'editProfile': 'Edit Profile',
      'logout': 'Logout',
      'myRooms': 'My Shifts',
      'noRoomAssigned': 'No room assigned',
      'noNotifications': 'No notifications',
      'createNewRoom': 'Create New Room',
      'roomName': 'Room Name',
      'description': 'Description',
      'firstDay': 'First Day',
      'lastDay': 'Last Day',
      'defaultShiftsCount': 'Default Number of Shifts',
      'enterDefaultShifts':
          'Enter default number of shifts for each participant',
      'editDailyShifts': 'Edit Daily Required Shifts',
      'setAllDaysTo': 'Set all days to:',
      'apply': 'Apply',
      'done': 'Done',
      'addParticipant': 'Add Participant',
      'participants': 'Participants:',
      'host': 'Host',
      'createRoom': 'Create Room',
      'confirmDelete': 'Confirm Delete',
      'sureToConfirmDeleteRoom': 'Are you sure you want to delete this room?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'unnamedRoom': 'Unnamed Room',
      'noDescription': 'No description',
      'invalidShifts': 'Invalid Shifts',
      'ok': 'OK',
      'signInToAccount': 'Sign in to your Account',
      'dontHaveAccount': 'Don\'t have an account?',
      'signUp': 'Sign Up',
      'forgotPassword': 'Forgot Your Password?',
      'enterValidEmailAndPassword': 'Please enter valid email and password.',
      'loginSuccessful': 'Login successful!',
      'loginFailed': 'Login failed. Please try again.',
      'firstDayBeforeToday': 'First day cannot be before today.',
      'lastDayBeforeFirstDay': 'Last day cannot be before first day.',
      'consecutiveDaysError':
          'The sum of shifts for any two consecutive days cannot exceed the total number of doctors.',
      'failedToCreateRoom': 'Failed to create room: ',
      'roomNameRequired': 'Room name is required.',
      'descriptionRequired': 'Description is required.',
      'firstDayRequired': 'First day is required.',
      'lastDayRequired': 'Last day is required.',
      'enterDefaultShiftsNumber': 'Please enter default number of shifts.',
      'enterValidNumber': 'Please enter a valid number.',
      'removeAssignment': 'Remove Assignment',
      'remove': 'Remove',
      'allParticipantsAssigned':
          'All participants are already assigned for this day.',
      'January': 'January',
      'February': 'February',
      'March': 'March',
      'April': 'April',
      'May': 'May',
      'June': 'June',
      'July': 'July',
      'August': 'August',
      'September': 'September',
      'October': 'October',
      'November': 'November',
      'December': 'December',
      'applySchedule': 'Apply Schedule',
      'previewSchedule': 'Preview Schedule',
      'failedToAddAssignment': 'Failed to add assignment: ',
      'failedToApplySchedule': 'Failed to apply schedule: ',
      'addAssignmentFor': 'Add assignment for: ',
      'removeAssignmentFor':
          'Do you want to remove "{username}" from the assignment on "{date}"?',
      'success': 'Success',
      'error': 'Error',
      'name': 'Name',
      'title': 'Title',
      'searchCountry': 'Search Country',
      'birthday': 'Birthday',
      'profileUpdated': 'Profile updated successfully!',
      'failedToUpdateProfile': 'Failed to update profile.',
      'applyChanges': 'Apply Changes',
      'roomNotFound': 'Room not found.',
      'failedToLoadData': 'Failed to load data.',
      'failedToJoinRoom': 'Failed to join room: ',
      'joiningAs': 'Joining as: ',
      'unknownUser': 'Unknown User',
      'noTitle': 'No Title',
      'joinRoom': 'Join Room',
      'unknownRoom': 'Unknown Room',
      'participantAssigned': 'Participant Assigned',
      'participantAssignedTo': 'This participant is already assigned to: ',
      'alreadyAssigned': 'Already Assigned',
      'assignedAlready': 'You are already joined to this room.',
      'assignParticipant': 'Assign Participant',
      'wantToAssign': 'Do you want to assign yourself to: ',
      'willNotAbleToUnassign': 'You won\'t be able to unassign yourself later.',
      'yes': 'Yes',
      'failedToAssign': 'Failed to assign participant: ',
      'hostCannotBeUnassigned': 'Host cannot be unassigned.',
      'removeAssignedUser': 'Do you want to remove the assigned user from: ',
      'removeParticipant': 'Remove Participant',
      'removeParticipantFromRoom':
          'Do you want to remove this participant from the room: ',
      'failedToRemoveUser': 'Failed to remove user: ',
      'cannotRemoveDoctor': 'Cannot Remove Doctor',
      'removeDoctorError':
          'Removing this doctor would result in consecutive days having more shifts than available doctors. Please adjust the daily shifts first.',
      'failedToRemoveParticipant': 'Failed to remove participant: ',
      'participantAlreadyExists':
          'A participant with this name already exists.',
      'failedToAddParticipant': 'Failed to add participant: ',
      'deleteRoom': 'Delete Room',
      'failedToDeleteRoom': 'Failed to delete room: ',
      'notAllowed': 'Not Allowed',
      'onlyHostShareInvitation': 'Only the host can share room invitations.',
      'invitationLink': 'Invitation Link',
      'linkCopied': 'The link has been copied to your clipboard.',
      'totalShiftsPerDoctor': 'Total Shifts Per Doctor',
      'close': 'Close',
      'totalShifts': 'Total Shifts',
      'all': 'All',
      'me': 'Me',
      'doNotHaveDuty': 'You don\'t have any duties in the schedule.',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'failedToRemoveAssignment': 'Failed to remove assignment: ',
      'roomDataNotFound': 'Room data not found.',
      'roomDataIncomplete': 'Room scheduling data is incomplete.',
      'failedToOpenDutiesScreen': 'Failed to open duties screen: ',
      'change': 'Change',
      'shiftsUpdated': 'Shifts Updated',
      'shiftsUpdatedSuccessfully':
          'Daily required shifts have been updated successfully.',
      'warning': 'Warning',
      'changingRoomDatesWarning':
          'Changing room dates will reset:\n\n• All doctors\' duty preferences\n• Number of shifts for each doctor\n• Daily required shifts (will be set to 1)\n• Any existing schedule\n\nDo you want to continue?',
      'continue': 'Continue',
      'yourHostUpdatedStartEndDates':
          'The host updated start and end date of your room "{roomName}". Please confirm your preferences.',
      'youUpdatedStartEndDates':
          'You updated start and end date of the room "{roomName}".',
      'roomUpdated': 'Room Updated',
      'roomDatesUpdated':
          'Room dates updated.\n\nAll preferences and schedules have been reset.\n\nPlease inform doctors to set their preferences again.',
      'failedToUpdateRoomDates': 'Failed to update room dates: ',
      'invalidSchedule': 'Invalid Schedule',
      'invalidScheduleError':
          'The number of days in the schedule should be at least twice the number of shifts of the doctor with the most shifts.',
      'numberOfDays': 'Number of Days: ',
      'doctorWithMostShifts': 'Doctor with the Most Shifts: ',
      'invalidScheduleError2':
          'The total number of shifts of the doctors should not be less than the total of the daily required shifts.',
      'totalDoctorShifts': 'Total Number of Shifts of the Doctors: ',
      'totalDailyShifts': 'Total of the Daily Required Shifts: ',
      'noDoctorsFound':
          'No doctors found in the room. Please add participants first.',
      'failedToFetchSchedule': 'Failed to fetch schedule: ',
      'errorOccurredWithError': 'Error occurred: ',
      'previewNewSchedule': 'Preview New Schedule',
      'editRoomDates': 'Edit Room Dates',
      'shareInvitation': 'Share Invitation',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'participantsTitle': 'Participants',
      'assignedTo': 'Assigned to: ',
      'editDuties': 'Edit Duties',
      'viewDuties': 'View Duties',
      'setDuties': 'Set Duties',
      'setShifts': 'Set Shift Numbers',
      'numberOfShifts': 'Number of Shifts',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'noPreferences': 'No Preference',
      'savePreferences': 'Save Preferences',
      'save': 'Save',
      'passwordAtLeast6Chars': 'Password must be at least 6 characters long.',
      'shiftCountUpdate': 'Shift Count Update',
      'shiftCountUpdatedSuccessfully': 'Shift count updated successfully.',
      'failedToUpdateShiftCount': 'Failed to update shift count: ',
      'preferences': '\'s Preferences',
      'requestedNumberOfShifts': 'Requested Number of Shifts: ',
      'update': 'Update',
      'availabilityCalendar': 'Availability Calendar: ',
      'pleaseEnterValidEmail': 'Please enter a valid email address',
      'failGoogleSignIn': 'Google sign-in was cancelled',
      'homeTitle': 'Nobetim',
      'aParticipant': 'A participant',
      'leftRoomMessage': '"{userName}" has left your room "{roomName}".',
      'scheduleAppliedMessage':
          'A new schedule has been applied in "{roomName}". Please check your new schedule.',
      'aUser': 'A user',
      'unNamedRoom': 'Unnamed Room',
      'roomJoinedOther':
          '"{userName}" joined the room "{roomName}" you are in.',
      'roomJoinedSelf': 'You joined "{roomName}"',
      'selfAssignmentMessage':
          '"{userName}" assigned themselves to "{participantName}" in room "{roomName}".',
      'unknown': 'Unknown',
      'today': 'Today',
      'onLeave': 'On Leave',
      'privacyPolicy': 'Privacy Policy',
      'exportExcel': 'Export to Excel',
      'noScheduleToExport': 'No schedule available to export',
      'failedToExportSchedule': 'Failed to export schedule',
    },
    'tr': {
      'today': 'Bugün',
      'unknown': 'Bilinmiyor',
      'selfAssignmentMessage':
          '"{userName}", "{roomName}" odasında kendisini "{participantName}" olarak atadı.',
      'roomJoinedSelf': '"{roomName}" odasına katıldınız.',
      'roomJoinedOther':
          '"{userName}", sizin de içinde bulunduğunuz "{roomName}" odasına katıldı.',
      'unNamedRoom': 'İsimsiz Oda',
      'aUser': 'Kullanıcı',
      'scheduleAppliedMessage':
          '"{roomName}" odasında yeni bir nöbet çizelgesi uygulanmıştır. Lütfen kontrol ediniz.',
      'leftRoomMessage': '"{userName}" odanızdan ayrıldı: "{roomName}".',
      'aParticipant': 'Katılımcı',
      'homeTitle': 'Nöbetim',
      'save': 'Kaydet',
      'appTitle': 'Nöbetim',
      'resetPassword': 'Parola Sıfırla',
      'resetPasswordEmailSent':
          'Parola sıfırlama e-postası gönderildi. E-postanı kontrol et!',
      'resetPasswordEmailFail':
          'Parola sıfırlama e-postası gönderilemedi. Tekrar dene.',
      'enterEmailToReceive': 'Sıfırlama linki için e-postanı gir',
      'enterYourEmail': 'E-postanı gir',
      'sendResetLink': 'Sıfırlama e-postası gönder',
      'pleaseEnterValidEmail': 'Lütfen geçerli bir e-posta girin',
      'failGoogleSignIn': 'Google girişi iptal edildi',
      'createAccount': 'Hesap Oluştur',
      'alreadyHaveAccount': 'Hesabınız var mı?',
      'login': 'Giriş Yap',
      'login2': 'Giriş Yap',
      'nameSurname': 'Ad & Soyad',
      'jobDescription': 'Ünvan',
      'selectBirthday': 'Doğum Tarihi Seç',
      'phoneNumber': 'Telefon Numarası',
      'email': 'Email',
      'password': 'Şifre',
      'register': 'Kayıt Ol',
      'registrationSuccessful': 'Kayıt başarılı!',
      'fillRequiredFields': 'Lütfen tüm zorunlu alanları doldurun.',
      'errorOccurred': 'Bir hata oluştu. Lütfen tekrar deneyin.',
      'editProfile': 'Profili Düzenle',
      'logout': 'Çıkış Yap',
      'myRooms': 'Nöbet Listelerim',
      'noRoomAssigned': 'Atanmış oda yok',
      'noNotifications': 'Bildirim yok',
      'createNewRoom': 'Yeni Oda Oluştur',
      'roomName': 'Oda Adı',
      'description': 'Açıklama',
      'firstDay': 'Başlangıç Tarihi',
      'lastDay': 'Bitiş Tarihi',
      'defaultShiftsCount': 'Varsayılan Kişi Başı Nöbet Sayısı',
      'enterDefaultShifts':
          'Her katılımcı için varsayılan nöbet sayısını girin',
      'editDailyShifts': 'Günlük Gerekli Nöbet Sayılarını Düzenle',
      'setAllDaysTo': 'Tüm günleri ayarla:',
      'apply': 'Uygula',
      'done': 'Tamamlandı',
      'addParticipant': 'Katılımcı Ekle',
      'participants': 'Katılımcılar:',
      'host': 'Yönetici',
      'createRoom': 'Oda Oluştur',
      'confirmDelete': 'Silmeyi Onaylayın',
      'sureToConfirmDeleteRoom': 'Bu odayı silmek istediğinizden emin misiniz?',
      'cancel': 'İptal',
      'delete': 'Sil',
      'unnamedRoom': 'İsimsiz Oda',
      'noDescription': 'Açıklama yok',
      'invalidShifts': 'Geçersiz Nöbet Sayıları',
      'ok': 'Tamam',
      'signInToAccount': 'Hesabınıza Giriş Yapın',
      'dontHaveAccount': 'Hesabınız yok mu?',
      'signUp': 'Kayıt Ol',
      'forgotPassword': 'Şifrenizi mi unuttunuz?',
      'enterValidEmailAndPassword': 'Lütfen geçerli bir email ve şifre girin.',
      'loginSuccessful': 'Giriş başarılı!',
      'loginFailed': 'Giriş başarısız. Lütfen tekrar deneyin.',
      'firstDayBeforeToday': 'Başlangıç tarihi bugünden önce olamaz.',
      'lastDayBeforeFirstDay': 'Bitiş tarihi başlangıç tarihinden önce olamaz.',
      'consecutiveDaysError':
          'İki ardışık gün için nöbet sayılarının toplamı, doktor sayısını aşamaz.',
      'failedToCreateRoom': 'Oda oluşturulamadı: ',
      'roomNameRequired': 'Oda adı gereklidir.',
      'descriptionRequired': 'Açıklama gereklidir.',
      'firstDayRequired': 'Başlangıç tarihi gereklidir.',
      'lastDayRequired': 'Bitiş tarihi gereklidir.',
      'enterDefaultShiftsNumber': 'Lütfen varsayılan nöbet sayısını girin.',
      'enterValidNumber': 'Lütfen geçerli bir sayı girin.',
      'removeAssignment': 'Atamayı Kaldır',
      'remove': 'Kaldır',
      'allParticipantsAssigned': 'Tüm katılımcılar zaten bu gün için atanmış.',
      'January': 'Ocak',
      'February': 'Şubat',
      'March': 'Mart',
      'April': 'Nisan',
      'May': 'Mayıs',
      'June': 'Haziran',
      'July': 'Temmuz',
      'August': 'Ağustos',
      'September': 'Eylül',
      'October': 'Ekim',
      'November': 'Kasım',
      'December': 'Aralık',
      'applySchedule': 'Programı Uygula',
      'previewSchedule': 'Programı Önizle',
      'failedToAddAssignment': 'Atama eklenemedi: ',
      'failedToApplySchedule': 'Program uygulanamadı: ',
      'addAssignmentFor': 'Şu tarih için atama ekle: ',
      'removeAssignmentFor':
          '"{username}" kişisinin "{date}" tarihindeki atamasını kaldırmak istiyor musunuz?',
      'success': 'Başarılı',
      'error': 'Hata',
      'name': 'Ad',
      'title': 'Ünvan',
      'searchCountry': 'Ülke Ara',
      'birthday': 'Doğum Günü',
      'profileUpdated': 'Profil başarıyla güncellendi!',
      'failedToUpdateProfile': 'Profil güncellenemedi.',
      'applyChanges': 'Değişiklikleri Uygula',
      'roomNotFound': 'Oda bulunamadı.',
      'failedToLoadData': 'Veriler yüklenemedi.',
      'failedToJoinRoom': 'Odaya katılma başarısız: ',
      'joiningAs': 'Şu kişi olarak katılınıyor: ',
      'unknownUser': 'Bilinmeyen Kullanıcı',
      'noTitle': 'Ünvan Yok',
      'joinRoom': 'Odaya Katıl',
      'unknownRoom': 'Bilinmeyen Oda',
      'participantAssigned': 'Katılımcı Zaten Atandı',
      'participantAssignedTo': 'Bu katılımcı zaten şu kişiye atanmış: ',
      'alreadyAssigned': 'Zaten Atandınız',
      'assignedAlready': 'Bu odaya zaten katılmışsınız.',
      'assignParticipant': 'Katılımcı Ata',
      'wantToAssign': 'Kendinizi şu kişiye atamak istiyor musunuz: ',
      'willNotAbleToUnassign':
          'Daha sonra kendinizi atamadan çıkaramayacaksınız.',
      'yes': 'Evet',
      'failedToAssign': 'Katılımcı atanamadı: ',
      'hostCannotBeUnassigned': 'Yönetici atamadan çıkarılamaz.',
      'removeAssignedUser': 'Şu kişiyi atamadan kaldırmak istiyor musunuz: ',
      'removeParticipant': 'Katılımcıyı Kaldır',
      'removeParticipantFromRoom':
          'Bu katılımcıyı odadan kaldırmak istiyor musunuz: ',
      'failedToRemoveUser': 'Kullanıcı kaldırılamadı: ',
      'cannotRemoveDoctor': 'Doktor Kaldırılamaz',
      'removeDoctorError':
          'Bu doktoru kaldırmak, ardışık günlerde nöbet sayısının toplam doktor sayısını aşmasına neden olur. Lütfen önce günlük nöbet sayılarını ayarlayın.',
      'failedToRemoveParticipant': 'Katılımcı kaldırılamadı: ',
      'participantAlreadyExists': 'Bu isimde bir katılımcı zaten var.',
      'failedToAddParticipant': 'Katılımcı eklenemedi: ',
      'deleteRoom': 'Odayı Sil',
      'failedToDeleteRoom': 'Oda silinemedi: ',
      'notAllowed': 'İzin Verilmedi',
      'onlyHostShareInvitation': 'Yalnızca oda yöneticisi davet paylaşabilir.',
      'invitationLink': 'Davet Linki',
      'linkCopied': 'Link panoya kopyalandı.',
      'totalShiftsPerDoctor': 'Doktor Başına Toplam Nöbet Sayısı',
      'close': 'Kapat',
      'totalShifts': 'Toplam Nöbet Sayıları',
      'all': 'Herkes',
      'me': 'Ben',
      'doNotHaveDuty': 'Programda herhangi bir nöbetiniz yok.',
      'monday': 'Pazartesi',
      'tuesday': 'Salı',
      'wednesday': 'Çarşamba',
      'thursday': 'Perşembe',
      'friday': 'Cuma',
      'saturday': 'Cumartesi',
      'sunday': 'Pazar',
      'failedToRemoveAssignment': 'Atama kaldırılamadı: ',
      'roomDataNotFound': 'Oda verisi bulunamadı.',
      'roomDataIncomplete': 'Oda programlama verileri eksik.',
      'failedToOpenDutiesScreen': 'Görev ekranı açılamadı: ',
      'change': 'Değiştir',
      'shiftsUpdated': 'Nöbetler Güncellendi',
      'shiftsUpdatedSuccessfully':
          'Günlük gerekli nöbet sayıları başarıyla güncellendi.',
      'warning': 'Uyarı',
      'changingRoomDatesWarning':
          'Oda tarihlerini değiştirmeniz, aşağıdakileri sıfırlayacaktır:\n\n• Tüm doktorların nöbet tercihleri\n• Her doktor için nöbet sayıları\n• Günlük gerekli nöbet sayıları (1 olarak ayarlanacak)\n• Mevcut programlar\n\nDevam etmek istiyor musunuz?',
      'continue': 'Devam',
      'yourHostUpdatedStartEndDates':
          'Yönetici, "{roomName}" odasının başlangıç ve bitiş tarihlerini değiştirdi. Lütfen tercihlerinizi güncelleyin.',
      'youUpdatedStartEndDates':
          '"{roomName}" odasının başlangıç ve bitiş tarihlerinizi güncellediniz.',
      'roomUpdated': 'Oda Güncellendi',
      'roomDatesUpdated':
          'Oda tarihleri güncellendi.\n\nTüm tercih ve programlar sıfırlandı.\n\nLütfen doktorların tercihlerini tekrar ayarlamalarını bildirin.',
      'failedToUpdateRoomDates': 'Oda tarihleri güncellenemedi: ',
      'invalidSchedule': 'Geçersiz Program',
      'invalidScheduleError':
          'Programdaki gün sayısı, en fazla nöbet sayısına sahip doktorun nöbet sayısının iki katından az olmamalıdır.',
      'numberOfDays': 'Gün Sayısı: ',
      'doctorWithMostShifts': 'En Fazla Nöbet Sayısına Sahip Doktor: ',
      'invalidScheduleError2':
          'Doktorların toplam nöbet sayısı, günlük gerekli nöbet sayılarının toplamından az olmamalıdır.',
      'totalDoctorShifts': 'Doktorların Toplam Nöbet Sayısı: ',
      'totalDailyShifts': 'Günlük Gerekli Nöbet Sayılarının Toplamı: ',
      'noDoctorsFound':
          'Odada doktor bulunamadı. Lütfen önce katılımcıları ekleyin.',
      'failedToFetchSchedule': 'Program alınamadı: ',
      'errorOccurredWithError': 'Hata oluştu: ',
      'previewNewSchedule': 'Yeni Program Önizle',
      'editRoomDates': 'Oda Tarihlerini Düzenle',
      'shareInvitation': 'Davet Paylaş',
      'mon': 'Pzt',
      'tue': 'Sal',
      'wed': 'Çar',
      'thu': 'Per',
      'fri': 'Cum',
      'sat': 'Cmt',
      'sun': 'Paz',
      'participantsTitle': 'Katılımcılar',
      'assignedTo': 'Atandı: ',
      'editDuties': 'Görevleri Düzenle',
      'viewDuties': 'Görevleri Görüntüle',
      'setDuties': 'Görevleri Ayarla',
      'setShifts': 'Nöbet Sayılarını Ayarla',
      'numberOfShifts': 'Nöbet Sayısı',
      'available': 'Müsait',
      'unavailable': 'Müsait Değil',
      'noPreferences': 'Tercih Yok',
      'savePreferences': 'Tercihleri Kaydet',
      'passwordAtLeast6Chars': 'Şifre en az 6 karakter uzunluğunda olmalıdır.',
      'shiftCountUpdate': 'Nöbet Sayısı Güncellemesi',
      'shiftCountUpdatedSuccessfully': 'Nöbet sayısı başarıyla güncellendi.',
      'failedToUpdateShiftCount': 'Nöbet sayısı güncellenemedi: ',
      'preferences': '\'in Tercihleri',
      'requestedNumberOfShifts': 'Talep Edilen Nöbet Sayısı: ',
      'update': 'Güncelle',
      'availabilityCalendar': 'Müsaitlik Takvimi: ',
      'onLeave': 'İzinli',
      'privacyPolicy': 'Gizlilik Politikası',
      'exportExcel': 'Excel\'e Aktar',
      'noScheduleToExport': 'Dışa aktarılacak program yok',
      'failedToExportSchedule': 'Program dışa aktarılamadı',
    },
  };

  String get(String key) {
    if (!_localizedValues[locale.languageCode]!.containsKey(key)) {
      debugPrint('❗Missing key "$key" for language ${locale.languageCode}');
    }
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key]!;
  }

  String translate(String key, {Map<String, String>? params}) {
    String? template = _localizedValues[locale.languageCode]?[key];

    if (template == null) return key;

    if (params != null) {
      params.forEach((placeholder, value) {
        template = template!.replaceAll('{$placeholder}', value);
      });
    }

    return template!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'tr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
