import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'createAccount': 'Create Account',
      'alreadyHaveAccount': 'Already have an account?',
      'login': 'Log in',
      'login2': 'Log In',
      'nameSurname': 'Name & Surname',
      'jobDescription': 'Job Description',
      'selectBirthday': 'Select Birthday',
      'phoneNumber': 'Phone Number',
      'email': 'Email',
      'password': 'Password',
      'register': 'Register',
      'registrationSuccessful': 'Registration successful!',
      'fillRequiredFields': 'Please fill in all required fields.',
      'errorOccurred': 'An error occurred. Please try again.',
      'editProfile': 'Edit Profile',
      'logout': 'Logout',
      'myRooms': 'My Rooms',
      'noRoomAssigned': 'No room assigned',
      'noNotifications': 'No notifications',
      'createNewRoom': 'Create New Room',
      'roomName': 'Room Name',
      'description': 'Description',
      'firstDay': 'First Day',
      'lastDay': 'Last Day',
      'defaultShiftsCount': 'Default Number of Shifts',
      'enterDefaultShifts': 'Enter default number of shifts for each participant',
      'editDailyShifts': 'Edit Daily Required Shifts',
      'setAllDaysTo': 'Set all days to:',
      'apply': 'Apply',
      'done': 'Done',
      'addParticipant': 'Add Participant',
      'participants': 'Participants:',
      'host': 'Host',
      'createRoom': 'Create Room',
      'confirmDelete': 'Confirm Delete',
      'sureToConfirmDeleteRoom': 'Are you sure you want to delete this room?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'unnamedRoom': 'Unnamed Room',
      'noDescription': 'No description',
      'invalidShifts': 'Invalid Shifts',
      'ok': 'OK',
      'signInToAccount': 'Sign in to your Account',
      'dontHaveAccount': 'Don\'t have an account?',
      'signUp': 'Sign Up',
      'forgotPassword': 'Forgot Your Password?',
      'enterValidEmailAndPassword': 'Please enter valid email and password.',
      'loginSuccessful': 'Login successful!',
      'loginFailed': 'Login failed. Please try again.',
      'firstDayBeforeToday': 'First day cannot be before today.',
      'lastDayBeforeFirstDay': 'Last day cannot be before first day.',
      'consecutiveDaysError': 'The sum of shifts for any two consecutive days cannot exceed the total number of doctors.',
      'failedToCreateRoom': 'Failed to create room: ', 
      'roomNameRequired': 'Room name is required.',
      'descriptionRequired': 'Description is required.',
      'firstDayRequired': 'First day is required.',
      'lastDayRequired': 'Last day is required.',
      'enterDefaultShiftsNumber': 'Please enter default number of shifts.',
      'enterValidNumber': 'Please enter a valid number.',
      'removeAssignment': 'Remove Assignment',
      'remove': 'Remove',
      'allParticipantsAssigned': 'All participants are already assigned for this day.',
      'January': 'January',
      'February': 'February',
      'March': 'March',
      'April': 'April',
      'May': 'May',
      'June': 'June',
      'July': 'July',
      'August': 'August',
      'September': 'September',
      'October': 'October',
      'November': 'November',
      'December': 'December',
      'applySchedule': 'Apply Schedule',
      'previewSchedule': 'Preview Schedule',
      'failedToAddAssignment': 'Failed to add assignment: ',
      'failedToApplySchedule': 'Failed to apply schedule: ',
      'addAssignmentFor': 'Add assignment for: ',
      'removeAssignmentFor': 'Do you want to remove this assignment?',
      'success': 'Success',
      'error': 'Error',
      'name': 'Name',
      'title': 'Title',
      'searchCountry': 'Search Country',
      'birthday': 'Birthday',
      'profileUpdated': 'Profile updated successfully!',
      'failedToUpdateProfile': 'Failed to update profile.',
      'applyChanges': 'Apply Changes'
      // ... add all other English strings
    },
    'tr': {
      'createAccount': 'Hesap Oluştur',
      'alreadyHaveAccount': 'Hesabınız var mı?',
      'login': 'Giriş Yap',
      'login2': 'Giriş Yap',
      'nameSurname': 'Ad & Soyad',
      'jobDescription': 'İş Tanımı',
      'selectBirthday': 'Doğum Tarihi Seç',
      'phoneNumber': 'Telefon Numarası',
      'email': 'Email',
      'password': 'Şifre',
      'register': 'Kayıt Ol',
      'registrationSuccessful': 'Kayıt başarılı!',
      'fillRequiredFields': 'Lütfen tüm zorunlu alanları doldurun.',
      'errorOccurred': 'Bir hata oluştu. Lütfen tekrar deneyin.',
      'editProfile': 'Profili Düzenle',
      'logout': 'Çıkış Yap',
      'myRooms': 'Odalarım',
      'noRoomAssigned': 'Atanmış oda yok',
      'noNotifications': 'Bildirim yok',
      'createNewRoom': 'Yeni Oda Oluştur',
      'roomName': 'Oda Adı',
      'description': 'Açıklama',
      'firstDay': 'Başlangıç Tarihi',
      'lastDay': 'Bitiş Tarihi',
      'defaultShiftsCount': 'Varsayılan Kişi Başı Nöbet Sayısı',
      'enterDefaultShifts': 'Her katılımcı için varsayılan nöbet sayısını girin',
      'editDailyShifts': 'Günlük Gerekli Nöbet Sayılarını Düzenle',
      'setAllDaysTo': 'Tüm günleri ayarla:',
      'apply': 'Uygula',
      'done': 'Tamamlandı',
      'addParticipant': 'Katılımcı Ekle',
      'participants': 'Katılımcılar:',
      'host': 'Yönetici',
      'createRoom': 'Oda Oluştur',
      'confirmDelete': 'Silmeyi Onaylayın',
      'sureToConfirmDeleteRoom': 'Bu odayı silmek istediğinizden emin misiniz?',
      'cancel': 'İptal',
      'delete': 'Sil',
      'unnamedRoom': 'İsimsiz Oda',
      'noDescription': 'Açıklama yok',
      'invalidShifts': 'Geçersiz Nöbet Sayıları',
      'ok': 'Tamam',
      'signInToAccount': 'Hesabınıza Giriş Yapın',
      'dontHaveAccount': 'Hesabınız yok mu?',
      'signUp': 'Kayıt Ol',
      'forgotPassword': 'Şifrenizi mi unuttunuz?',
      'enterValidEmailAndPassword': 'Lütfen geçerli bir email ve şifre girin.',
      'loginSuccessful': 'Giriş başarılı!',
      'loginFailed': 'Giriş başarısız. Lütfen tekrar deneyin.',
      'firstDayBeforeToday': 'Başlangıç tarihi bugünden önce olamaz.',
      'lastDayBeforeFirstDay': 'Bitiş tarihi başlangıç tarihinden önce olamaz.',
      'consecutiveDaysError': 'İki ardışık gün için nöbet sayılarının toplamı, doktor sayısını aşamaz.',
      'failedToCreateRoom': 'Oda oluşturulamadı: ',
      'roomNameRequired': 'Oda adı gereklidir.',
      'descriptionRequired': 'Açıklama gereklidir.',
      'firstDayRequired': 'Başlangıç tarihi gereklidir.',
      'lastDayRequired': 'Bitiş tarihi gereklidir.',
      'enterDefaultShiftsNumber': 'Lütfen varsayılan nöbet sayısını girin.',
      'enterValidNumber': 'Lütfen geçerli bir sayı girin.',
      'removeAssignment': 'Atamayı Kaldır',
      'remove': 'Kaldır',
      'allParticipantsAssigned': 'Tüm katılımcılar zaten bu gün için atanmış.',
      'January': 'Ocak',
      'February': 'Şubat',
      'March': 'Mart',
      'April': 'Nisan',
      'May': 'Mayıs',
      'June': 'Haziran',
      'July': 'Temmuz',
      'August': 'Ağustos',
      'September': 'Eylül',
      'October': 'Ekim',
      'November': 'Kasım',
      'December': 'Aralık',
      'applySchedule': 'Programı Uygula',
      'previewSchedule': 'Programı Önizle',
      'failedToAddAssignment': 'Atama eklenemedi: ',
      'failedToApplySchedule': 'Program uygulanamadı: ',
      'addAssignmentFor': 'Şu tarih için atama ekle: ',
      'removeAssignmentFor': 'Bu atamayı kaldırmak istiyor musunuz?',
      'success': 'Başarılı',
      'error': 'Hata',
      'name': 'Ad',
      'title': 'Ünvan',
      'searchCountry': 'Ülke Ara',
      'birthday': 'Doğum Günü',
      'profileUpdated': 'Profil başarıyla güncellendi!',
      'failedToUpdateProfile': 'Profil güncellenemedi.',
      'applyChanges': 'Değişiklikleri Uygula',
      // ... add all other Turkish strings
    }
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']![key]!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'tr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
