import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'createAccount': 'Create Account',
      'alreadyHaveAccount': 'Already have an account?',
      'login': 'Log in',
      'login2': 'Log In',
      'nameSurname': 'Name & Surname',
      'jobDescription': 'Job Description',
      'selectBirthday': 'Select Birthday',
      'phoneNumber': 'Phone Number',
      'email': 'Email',
      'password': 'Password',
      'register': 'Register',
      'registrationSuccessful': 'Registration successful!',
      'fillRequiredFields': 'Please fill in all required fields.',
      'errorOccurred': 'An error occurred. Please try again.',
      'editProfile': 'Edit Profile',
      'logout': 'Logout',
      'myRooms': 'My Rooms',
      'noRoomAssigned': 'No room assigned',
      'noNotifications': 'No notifications',
      'createNewRoom': 'Create New Room',
      'roomName': 'Room Name',
      'description': 'Description',
      'firstDay': 'First Day',
      'lastDay': 'Last Day',
      'defaultShiftsCount': 'Default Number of Shifts',
      'enterDefaultShifts': 'Enter default number of shifts for each participant',
      'editDailyShifts': 'Edit Daily Required Shifts',
      'setAllDaysTo': 'Set all days to:',
      'apply': 'Apply',
      'done': 'Done',
      'addParticipant': 'Add Participant',
      'participants': 'Participants:',
      'host': 'Host',
      'createRoom': 'Create Room',
      'confirmDelete': 'Confirm Delete',
      'sureToConfirmDeleteRoom': 'Are you sure you want to delete this room?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'unnamedRoom': 'Unnamed Room',
      'noDescription': 'No description',
      'invalidShifts': 'Invalid Shifts',
      'ok': 'OK',
      'signInToAccount': 'Sign in to your Account',
      'dontHaveAccount': 'Don\'t have an account?',
      'signUp': 'Sign Up',
      'forgotPassword': 'Forgot Your Password?',
      'enterValidEmailAndPassword': 'Please enter valid email and password.',
      'loginSuccessful': 'Login successful!',
      'loginFailed': 'Login failed. Please try again.',
      'firstDayBeforeToday': 'First day cannot be before today.',
      'lastDayBeforeFirstDay': 'Last day cannot be before first day.',
      'consecutiveDaysError': 'The sum of shifts for any two consecutive days cannot exceed the total number of doctors.',
      'failedToCreateRoom': 'Failed to create room: ', 
      'roomNameRequired': 'Room name is required.',
      'descriptionRequired': 'Description is required.',
      'firstDayRequired': 'First day is required.',
      'lastDayRequired': 'Last day is required.',
      'enterDefaultShiftsNumber': 'Please enter default number of shifts.',
      'enterValidNumber': 'Please enter a valid number.',
      'removeAssignment': 'Remove Assignment',
      'remove': 'Remove',
      'allParticipantsAssigned': 'All participants are already assigned for this day.',
      'January': 'January',
      'February': 'February',
      'March': 'March',
      'April': 'April',
      'May': 'May',
      'June': 'June',
      'July': 'July',
      'August': 'August',
      'September': 'September',
      'October': 'October',
      'November': 'November',
      'December': 'December',
      'applySchedule': 'Apply Schedule',
      'previewSchedule': 'Preview Schedule',
      'failedToAddAssignment': 'Failed to add assignment: ',
      'failedToApplySchedule': 'Failed to apply schedule: ',
      'addAssignmentFor': 'Add assignment for: ',
      'removeAssignmentFor': 'Do you want to remove this assignment?',
      'success': 'Success',
      'error': 'Error',
      'name': 'Name',
      'title': 'Title',
      'searchCountry': 'Search Country',
      'birthday': 'Birthday',
      'profileUpdated': 'Profile updated successfully!',
      'failedToUpdateProfile': 'Failed to update profile.',
      'applyChanges': 'Apply Changes',
      'roomNotFound': 'Room not found.',
      'failedToLoadData': 'Failed to load data.',
      'failedToJoinRoom': 'Failed to join room: ',
      'joiningAs': 'Joining as: ',
      'unknownUser': 'Unknown User',
      'noTitle': 'No Title',
      'joinRoom': 'Join Room: ',
      'unknownRoom': 'Unknown Room',
      'participantAssigned': 'Participant Assigned',
      'participantAssignedTo': 'This participant is already assigned to: ',
      'alreadyAssigned': 'Already Assigned',
      'assignedAlready': 'You are already assigned to another participant in this room.',
      'assignParticipant': 'Assign Participant',
      'wantToAssing': 'Do you want to assign yourself to: ',
      'willNotAbleToUnassign': 'You won\'t be able to unassign yourself later.',
      'yes': 'Yes',
      'failedToAssign': 'Failed to assign participant: ',
      'hostCannotBeUnassigned': 'Host cannot be unassigned.',
      'removeAssignedUser': 'Do you want to remove the assigned user from: ',
      'removeParticipant': 'Remove Participant',
      'removeParticipantFromRoom': 'Do you want to remove this participant from the room: ',
      'failedToRemoveUser': 'Failed to remove user: ',
      'cannotRemoveDoctor': 'Cannot Remove Doctor',
      'removeDoctorError': 'Removing this doctor would result in consecutive days having more '
                           'shifts than available doctors. Please adjust the daily shifts first.',
      'failedToRemoveParticipant': 'Failed to remove participant: ',
      'participantAlreadyExists': 'A participant with this name already exists.',
      'failedToAddParticipant': 'Failed to add participant: ',
      'deleteRoom': 'Delete Room',
      'failedToDeleteRoom': 'Failed to delete room: ',
      'notAllowed': 'Not Allowed',
      'onlyHostShareInvitation': 'Only the host can share room invitations.',
      'invitationLink': 'Invitation Link',
      'linkCopied': 'The link has been copied to your clipboard.',
      'totalShiftsPerDoctor': 'Total Shifts Per Doctor',
      'close': 'Close',
      'totalShifts': 'Total Shifts',
      'all': 'All',
      'me': 'Me',
      'doNotHaveDuty': 'You don\'t have any duties in the schedule.',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'failedToRemoveAssignment': 'Failed to remove assignment: ',
      'roomDataNotFound': 'Room data not found.',
      'roomDataIncomplete': 'Room scheduling data is incomplete.',
      'failedToOpenDutiesScreen': 'Failed to open duties screen: ',
      'change': 'Change',
      'shiftsUpdated': 'Shifts Updated',
      'shiftsUpdatedSuccessfully': 'Daily required shifts have been updated successfully.',
      'warning': 'Warning',
      'changingRoomDatesWarning': 'Changing room dates will reset:\n\n'
                                  '• All doctors\' duty preferences\n'
                                  '• Number of shifts for each doctor\n'
                                  '• Daily required shifts (will be set to 1)\n'
                                  '• Any existing schedule\n\n'
                                  'Do you want to continue?',
      'continue': 'Continue',
      'yourHostUpdatedStartEndDates': 'Your host updated start and end date. Please confirm your preferences.',
      'youUpdatedStartEndDates': 'You updated start and end date',
      'roomUpdated': 'Room Updated',
      'roomDatesUpdated': 'Room dates updated.\n\nAll preferences and schedules have been reset.\n\nPlease inform doctors to set their preferences again.',
      'failedToUpdateRoomDates': 'Failed to update room dates: ',
      'invalidSchedule': 'Invalid Schedule',
      'invalidScheduleError': 'The number of days in the schedule should be at least twice the number of shifts of the doctor with the most shifts.',
      'numberOfDays': 'Number of Days: ',
      'doctorWithMostShifts': 'Doctor with the Most Shifts: ',
      'invalidScheduleError2': 'The total number of shifts of the doctors should not be less than the total of the daily required shifts.',
      'totalDoctorShifts': 'Total Number of Shifts of the Doctors: ',
      'totalDailyShifts': 'Total of the Daily Required Shifts: ',
      'noDoctorsFound': 'No doctors found in the room. Please add participants first.',
      'failedToFetchSchedule': 'Failed to fetch schedule: ',
      'errorOccurredWithError': 'Error occurred: ',
      'previewNewSchedule': 'Preview New Schedule',
      'editRoomDates': 'Edit Room Dates',
      'shareInvitation': 'Share Invitation',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'participantsTitle': 'Participants',
      'assignedTo': 'Assigned to: ',
      'editDuties': 'Edit Duties',
      'viewDuties': 'View Duties',
      'setDuties': 'Set Duties',
      'setShifts': 'Set Shift Numbers',
      'numberOfShifts': 'Number of Shifts',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'noPreferences': 'No Preference',
      'savePreferences': 'Save Preferences',
      'passwordAtLeast6Chars': 'Password must be at least 6 characters long.',
      // ... add all other English strings
    },
    'tr': {
      'createAccount': 'Hesap Oluştur',
      'alreadyHaveAccount': 'Hesabınız var mı?',
      'login': 'Giriş Yap',
      'login2': 'Giriş Yap',
      'nameSurname': 'Ad & Soyad',
      'jobDescription': 'İş Tanımı',
      'selectBirthday': 'Doğum Tarihi Seç',
      'phoneNumber': 'Telefon Numarası',
      'email': 'Email',
      'password': 'Şifre',
      'register': 'Kayıt Ol',
      'registrationSuccessful': 'Kayıt başarılı!',
      'fillRequiredFields': 'Lütfen tüm zorunlu alanları doldurun.',
      'errorOccurred': 'Bir hata oluştu. Lütfen tekrar deneyin.',
      'editProfile': 'Profili Düzenle',
      'logout': 'Çıkış Yap',
      'myRooms': 'Odalarım',
      'noRoomAssigned': 'Atanmış oda yok',
      'noNotifications': 'Bildirim yok',
      'createNewRoom': 'Yeni Oda Oluştur',
      'roomName': 'Oda Adı',
      'description': 'Açıklama',
      'firstDay': 'Başlangıç Tarihi',
      'lastDay': 'Bitiş Tarihi',
      'defaultShiftsCount': 'Varsayılan Kişi Başı Nöbet Sayısı',
      'enterDefaultShifts': 'Her katılımcı için varsayılan nöbet sayısını girin',
      'editDailyShifts': 'Günlük Gerekli Nöbet Sayılarını Düzenle',
      'setAllDaysTo': 'Tüm günleri ayarla:',
      'apply': 'Uygula',
      'done': 'Tamamlandı',
      'addParticipant': 'Katılımcı Ekle',
      'participants': 'Katılımcılar:',
      'host': 'Yönetici',
      'createRoom': 'Oda Oluştur',
      'confirmDelete': 'Silmeyi Onaylayın',
      'sureToConfirmDeleteRoom': 'Bu odayı silmek istediğinizden emin misiniz?',
      'cancel': 'İptal',
      'delete': 'Sil',
      'unnamedRoom': 'İsimsiz Oda',
      'noDescription': 'Açıklama yok',
      'invalidShifts': 'Geçersiz Nöbet Sayıları',
      'ok': 'Tamam',
      'signInToAccount': 'Hesabınıza Giriş Yapın',
      'dontHaveAccount': 'Hesabınız yok mu?',
      'signUp': 'Kayıt Ol',
      'forgotPassword': 'Şifrenizi mi unuttunuz?',
      'enterValidEmailAndPassword': 'Lütfen geçerli bir email ve şifre girin.',
      'loginSuccessful': 'Giriş başarılı!',
      'loginFailed': 'Giriş başarısız. Lütfen tekrar deneyin.',
      'firstDayBeforeToday': 'Başlangıç tarihi bugünden önce olamaz.',
      'lastDayBeforeFirstDay': 'Bitiş tarihi başlangıç tarihinden önce olamaz.',
      'consecutiveDaysError': 'İki ardışık gün için nöbet sayılarının toplamı, doktor sayısını aşamaz.',
      'failedToCreateRoom': 'Oda oluşturulamadı: ',
      'roomNameRequired': 'Oda adı gereklidir.',
      'descriptionRequired': 'Açıklama gereklidir.',
      'firstDayRequired': 'Başlangıç tarihi gereklidir.',
      'lastDayRequired': 'Bitiş tarihi gereklidir.',
      'enterDefaultShiftsNumber': 'Lütfen varsayılan nöbet sayısını girin.',
      'enterValidNumber': 'Lütfen geçerli bir sayı girin.',
      'removeAssignment': 'Atamayı Kaldır',
      'remove': 'Kaldır',
      'allParticipantsAssigned': 'Tüm katılımcılar zaten bu gün için atanmış.',
      'January': 'Ocak',
      'February': 'Şubat',
      'March': 'Mart',
      'April': 'Nisan',
      'May': 'Mayıs',
      'June': 'Haziran',
      'July': 'Temmuz',
      'August': 'Ağustos',
      'September': 'Eylül',
      'October': 'Ekim',
      'November': 'Kasım',
      'December': 'Aralık',
      'applySchedule': 'Programı Uygula',
      'previewSchedule': 'Programı Önizle',
      'failedToAddAssignment': 'Atama eklenemedi: ',
      'failedToApplySchedule': 'Program uygulanamadı: ',
      'addAssignmentFor': 'Şu tarih için atama ekle: ',
      'removeAssignmentFor': 'Bu atamayı kaldırmak istiyor musunuz?',
      'success': 'Başarılı',
      'error': 'Hata',
      'name': 'Ad',
      'title': 'Ünvan',
      'searchCountry': 'Ülke Ara',
      'birthday': 'Doğum Günü',
      'profileUpdated': 'Profil başarıyla güncellendi!',
      'failedToUpdateProfile': 'Profil güncellenemedi.',
      'applyChanges': 'Değişiklikleri Uygula',
      'roomNotFound': 'Oda bulunamadı.',
      'failedToLoadData': 'Veriler yüklenemedi.',
      'failedToJoinRoom': 'Odaya katılma başarısız: ',
      'joiningAs': 'Şu kişi olarak katılınıyor: ',
      'unknownUser': 'Bilinmeyen Kullanıcı',
      'noTitle': 'Ünvan Yok',
      'joinRoom': 'Odaya Katıl: ',
      'unknownRoom': 'Bilinmeyen Oda',
      'participantAssigned': 'Katılımcı Zaten Atandı',
      'participantAssignedTo': 'Bu katılımcı zaten şu kişiye atanmış: ',
      'alreadyAssigned': 'Zaten Atandınız',
      'assignedAlready': 'Bu odada zaten başka bir katılımcıya atanmışsınız.',
      'assignParticipant': 'Katılımcı Ata',
      'wantToAssing': 'Kendinizi şu kişiye atamak istiyor musunuz: ',
      'willNotAbleToUnassign': 'Daha sonra kendinizi atamadan çıkaramayacaksınız.',
      'yes': 'Evet',
      'failedToAssign': 'Katılımcı atanamadı: ',
      'hostCannotBeUnassigned': 'Yönetici atamadan çıkarılamaz.',
      'removeAssignedUser': 'Şu kişiyi atamadan kaldırmak istiyor musunuz: ',
      'removeParticipant': 'Katılımcıyı Kaldır',
      'removeParticipantFromRoom': 'Bu katılımcıyı odadan kaldırmak istiyor musunuz: ',
      'failedToRemoveUser': 'Kullanıcı kaldırılamadı: ',
      'cannotRemoveDoctor': 'Doktor Kaldırılamaz',
      'removeDoctorError': 'Bu doktoru kaldırmak, ardışık günlerde nöbet sayısının toplam doktor sayısını aşmasına neden olur. '
                           'Lütfen önce günlük nöbet sayılarını ayarlayın.',
      'failedToRemoveParticipant': 'Katılımcı kaldırılamadı: ',
      'participantAlreadyExists': 'Bu isimde bir katılımcı zaten var.',
      'failedToAddParticipant': 'Katılımcı eklenemedi: ',
      'deleteRoom': 'Odayı Sil',
      'failedToDeleteRoom': 'Oda silinemedi: ',
      'notAllowed': 'İzin Verilmedi',
      'onlyHostShareInvitation': 'Yalnızca oda yöneticisi davet paylaşabilir.',
      'invitationLink': 'Davet Linki',
      'linkCopied': 'Link panoya kopyalandı.',
      'totalShiftsPerDoctor': 'Doktor Başına Toplam Nöbet Sayısı',
      'close': 'Kapat',
      'totalShifts': 'Toplam Nöbet Sayıları',
      'all': 'Herkes',
      'me': 'Ben',
      'doNotHaveDuty': 'Programda herhangi bir nöbetiniz yok.',
      'monday': 'Pazartesi',
      'tuesday': 'Salı',
      'wednesday': 'Çarşamba',
      'thursday': 'Perşembe',
      'friday': 'Cuma',
      'saturday': 'Cumartesi',
      'sunday': 'Pazar',
      'failedToRemoveAssignment': 'Atama kaldırılamadı: ',
      'roomDataNotFound': 'Oda verisi bulunamadı.',
      'roomDataIncomplete': 'Oda programlama verileri eksik.',
      'failedToOpenDutiesScreen': 'Görev ekranı açılamadı: ',
      'change': 'Değiştir',
      'shiftsUpdated': 'Nöbetler Güncellendi',
      'shiftsUpdatedSuccessfully': 'Günlük gerekli nöbet sayıları başarıyla güncellendi.',
      'warning': 'Uyarı',
      'changingRoomDatesWarning': 'Oda tarihlerini değiştirmeniz durumunda:\n\n'
                                  '• Tüm doktorların nöbet tercihleri sıfırlanacak,\n'
                                  '• Her doktor için nöbet sayısı sıfırlanacak,\n'
                                  '• Günlük gerekli nöbet sayıları 1 olarak ayarlanacak,\n'
                                  '• Mevcut program silinecek.\n\n'
                                  'Devam etmek istiyor musunuz?',
      'continue': 'Devam',
      'yourHostUpdatedStartEndDates': 'Yönetici başlangıç ve bitiş tarihlerini değiştirdi. Lütfen tercihlerinizi güncelleyin.',
      'youUpdatedStartEndDates': 'Başlangıç ve bitiş tarihlerinizi güncellediniz.',
      'roomUpdated': 'Oda Güncellendi',
      'roomDatesUpdated': 'Oda tarihleri güncellendi.\n\nTüm tercih ve programlar sıfırlandı.\n\nLütfen doktorların tercihlerini tekrar ayarlamalarını bildirin.',
      'failedToUpdateRoomDates': 'Oda tarihleri güncellenemedi: ',
      'invalidSchedule': 'Geçersiz Program',
      'invalidScheduleError': 'Programdaki gün sayısı, en fazla nöbet sayısına sahip doktorun nöbet sayısının iki katından az olmamalıdır.',
      'numberOfDays': 'Gün Sayısı: ',
      'doctorWithMostShifts': 'En Fazla Nöbet Sayısına Sahip Doktor: ',
      'invalidScheduleError2': 'Doktorların toplam nöbet sayısı, günlük gerekli nöbet sayılarının toplamından az olmamalıdır.',
      'totalDoctorShifts': 'Doktorların Toplam Nöbet Sayısı: ',
      'totalDailyShifts': 'Günlük Gerekli Nöbet Sayılarının Toplamı: ',
      'noDoctorsFound': 'Odada doktor bulunamadı. Lütfen önce katılımcıları ekleyin.',
      'failedToFetchSchedule': 'Program alınamadı: ',
      'errorOccurredWithError': 'Hata oluştu: ',
      'previewNewSchedule': 'Yeni Program Önizle',
      'editRoomDates': 'Oda Tarihlerini Düzenle',
      'shareInvitation': 'Davet Paylaş',
      'mon': 'Pzt',
      'tue': 'Sal',
      'wed': 'Çar',
      'thu': 'Per',
      'fri': 'Cum',
      'sat': 'Cmt',
      'sun': 'Paz',
      'participantsTitle': 'Katılımcılar',
      'assignedTo': 'Atandı: ',
      'editDuties': 'Görevleri Düzenle',
      'viewDuties': 'Görevleri Görüntüle',
      'setDuties': 'Görevleri Ayarla',
      'setShifts': 'Nöbet Sayılarını Ayarla',
      'numberOfShifts': 'Nöbet Sayısı',
      'available': 'Müsait',
      'unavailable': 'Müsait Değil',
      'noPreferences': 'Tercih Yok',
      'savePreferences': 'Tercihleri Kaydet',
      'passwordAtLeast6Chars': 'Şifre en az 6 karakter uzunluğunda olmalıdır.',
      // ... add all other Turkish strings
    }
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']![key]!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'tr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
