// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxNCg08c9nnv1mcEcqOcroa-oWrCn8c8',
    appId: '1:801988041686:web:1fcaffeae36cfab52fa277',
    messagingSenderId: '801988041686',
    projectId: 'scheduling-system-comp491',
    authDomain: 'scheduling-system-comp491.firebaseapp.com',
    storageBucket: 'scheduling-system-comp491.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43AWyEteqHSbR2YtHTUrNSYMzkOSy0U0',
    appId: '1:801988041686:android:59c8577fa9cc846f2fa277',
    messagingSenderId: '801988041686',
    projectId: 'scheduling-system-comp491',
    storageBucket: 'scheduling-system-comp491.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_-dPaazP_JaZpBzQ6OXlPfwwG4UrJbA',
    appId: '1:801988041686:ios:9e3c8da242b3868f2fa277',
    messagingSenderId: '801988041686',
    projectId: 'scheduling-system-comp491',
    storageBucket: 'scheduling-system-comp491.firebasestorage.app',
    iosBundleId: 'com.example.project491',
  );
}
